name: Echo Deploy

on: [push]

jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Echo Message
        run: echo "✅ To-Do App pushed and GitHub Action ran successfully!"
